// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkShop.Core.Entities;

public partial class Menu
{
    public int MenuId { get; set; }

    public string MenuCode { get; set; }

    public string MenuName { get; set; }

    public int? ParentMenuId { get; set; }

    public int SortOrder { get; set; }

    public string ControllerName { get; set; }

    public string ActionName { get; set; }

    public byte IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<Menu> InverseParentMenu { get; set; } = new List<Menu>();

    public virtual Menu ParentMenu { get; set; }

    public virtual ICollection<RoleMenuPermission> RoleMenuPermissions { get; set; } = new List<RoleMenuPermission>();
}