// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkShop.Core.Entities;

public partial class RoleMenuPermission
{
    public int RoleId { get; set; }

    public int MenuId { get; set; }

    /// <summary>
    /// bit flags: 1=Read, 2=Modify, 4=Delete
    /// </summary>
    public int Permission { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Role Role { get; set; }
}